Fix build problems on Python 3.5 on macOS:
Traceback (most recent call last):
  File "/Users/travis/venv/lib/python3.5/site-packages/starforge/commands/cmd_wheel.py", line 77, in cli
    check_wheel_source(forge.cache_manager, forge.wheel_config)
  File "/Users/travis/venv/lib/python3.5/site-packages/starforge/cache.py", line 253, in check_wheel_source
    assert cached_source is not None, 'Cache failure on: %s' % missing
AssertionError: Cache failure on: https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/travis/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Users/travis/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/Users/travis/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/Users/travis/venv/lib/python3.5/site-packages/urllib3/connection.py", line 350, in connect
    ssl_context=context)
  File "/Users/travis/venv/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:719)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/travis/venv/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/travis/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/travis/venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gmplib.org', port=443): Max retries exceeded with url: /download/gmp/gmp-6.1.2.tar.bz2 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:719)'),))